export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const STOP_NOTIFICATION = 'STOP_NOTIFICATION'

export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL'
export const EMPTY_ADD_WARNING = 'EMPTY_ADD_WARNING'

export const LOAD_TODO_SUCCESS = 'LOAD_TODO_SUCCESS'
export const LOAD_TODO_FAIL = 'LOAD_TODO_FAIL'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL'
export const EMPTY_DELETE_WARNING = 'EMPTY_DELETE_WARNING'

export const MARKDONE_TODO_SUCCESS = 'MARKDONE_TODO_SUCCESS'
export const MARKDONE_TODO_FAIL = 'MARKDONE_TODO_FAIL'

export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const EDIT_TODO_FAIL = 'EDIT_TODO_FAIL'

